version: '3.3'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: healthcare_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: patel
    ports:
      - "5433:5432"

  backend:
    build: ./demo
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/healthcare_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: patel
    depends_on:
      - postgres

  frontend:
    build: ./patient-management-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

