spring:
  application:
    name: healthcare-records-api

  datasource:
    url: jdbc:postgresql://localhost:5433/healthcare_db
    username: postgres
    password: patel

  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect